// react-app/src/features/customers/CustomerDetail.tsx
import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';

import { useAppDispatch, useAppSelector } from '../../app/hooks';
import {
  fetchCustomerById,
  clearSelected,
  selectSelectedCustomer,
  selectSelectedStatus
} from './customersSlice';
import styles from './CustomerDetail.module.css';

/**
 * Shows one customer. The id comes from the URL (/customers/:id), read with the
 * router's useParams hook.
 */
export function CustomerDetail() {
  const dispatch = useAppDispatch();
  // useParams returns the dynamic segments of the matched route.
  const { id } = useParams<{ id: string }>();

  const customer = useAppSelector(selectSelectedCustomer);
  const status = useAppSelector(selectSelectedStatus);

  useEffect(() => {
    if (id) {
      dispatch(fetchCustomerById(id));
    }
    // The cleanup function returned from useEffect runs when the component
    // unmounts — here we clear the selected customer so it does not flash on
    // the next detail screen.
    return () => {
      dispatch(clearSelected());
    };
  }, [dispatch, id]);

  return (
    <section>
      <header className={styles.header}>
        <h1>Customer details</h1>
        <Link className="btn btn--ghost" to="/customers">
          ← Back to list
        </Link>
      </header>

      {status === 'loading' && <p className="muted">Loading…</p>}
      {status === 'failed' && <p className="alert alert--error">Customer not found.</p>}

      {status === 'succeeded' && customer && (
        <>
          {/* A <dl> (description list) is the semantic element for label/value pairs. */}
          <dl className={styles.details}>
            <dt>Full name</dt>
            <dd>{customer.fullName}</dd>

            <dt>Email</dt>
            <dd>{customer.email}</dd>

            <dt>Phone</dt>
            <dd>{customer.phone}</dd>

            <dt>Created</dt>
            <dd>{customer.createdAtUtc}</dd>

            <dt>Last updated</dt>
            <dd>{customer.updatedAtUtc}</dd>
          </dl>

          <Link className="btn btn--primary" to={`/customers/${customer.id}/edit`}>
            Edit
          </Link>
        </>
      )}
    </section>
  );
}

// angular-app/src/app/features/customers/customer-detail/customer-detail.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';

import { CustomerService } from '../../../core/customer.service';
import { Customer } from '../../../models/customer.model';

/**
 * Shows a single customer. The id comes from the URL (/customers/:id), which we
 * read from the ActivatedRoute.
 */
@Component({
  selector: 'app-customer-detail',
  imports: [RouterLink],
  templateUrl: './customer-detail.component.html',
  styleUrl: './customer-detail.component.scss'
})
export class CustomerDetailComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly customerService = inject(CustomerService);

  readonly customer = signal<Customer | null>(null);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  ngOnInit(): void {
    // snapshot reads the route params once, at load time — fine here because we
    // navigate to a fresh component instance per customer.
    const id = this.route.snapshot.paramMap.get('id');
    if (!id) {
      this.error.set('No customer id in the URL.');
      this.loading.set(false);
      return;
    }

    this.customerService.getById(id).subscribe({
      next: (data) => {
        this.customer.set(data);
        this.loading.set(false);
      },
      error: () => {
        this.error.set('Customer not found.');
        this.loading.set(false);
      }
    });
  }
}

<section class="page">
  <header class="page__header">
    <h1>Customer details</h1>
    <a class="btn btn--ghost" routerLink="/customers">← Back to list</a>
  </header>

  @if (loading()) {
    <p class="muted">Loading…</p>
  } @else if (error()) {
    <p class="alert alert--error">{{ error() }}</p>
  } @else {
    <!--
      The `; as c` alias is only allowed on a PRIMARY @if (not on @else if), so we
      open a fresh @if here. It reads the signal once and aliases it to `c`, so
      inside this block we can use c.* without repeating the null check.
      A <dl> (description list) is the semantic element for label/value pairs.
    -->
    @if (customer(); as c) {
    <dl class="details">
      <dt>Full name</dt>
      <dd>{{ c.fullName }}</dd>

      <dt>Email</dt>
      <dd>{{ c.email }}</dd>

      <dt>Phone</dt>
      <dd>{{ c.phone }}</dd>

      <dt>Created</dt>
      <dd>{{ c.createdAtUtc }}</dd>

      <dt>Last updated</dt>
      <dd>{{ c.updatedAtUtc }}</dd>
    </dl>

    <div class="actions">
      <a class="btn btn--primary" [routerLink]="['/customers', c.id, 'edit']">Edit</a>
    </div>
    }
  }
</section>
