// react-app/src/features/customers/CustomerList.tsx
import { useEffect } from 'react';
import { Link } from 'react-router-dom';

import { useAppDispatch, useAppSelector } from '../../app/hooks';
import {
  fetchCustomers,
  deleteCustomer,
  selectCustomers,
  selectCustomersStatus,
  selectCustomersError
} from './customersSlice';
import type { Customer } from '../../types/customer';
import styles from './CustomerList.module.css';

/**
 * Shows every customer in a table. This component demonstrates the full Redux
 * read/write loop:
 *   - READ state with useAppSelector(selector)
 *   - WRITE by dispatching a thunk: dispatch(fetchCustomers())
 */
export function CustomerList() {
  const dispatch = useAppDispatch();

  // Each selector subscribes the component to that slice of state. When the
  // value changes, React re-renders this component.
  const customers = useAppSelector(selectCustomers);
  const status = useAppSelector(selectCustomersStatus);
  const error = useAppSelector(selectCustomersError);

  // useEffect runs after render. With an empty dependency array `[]` it runs
  // ONCE when the component mounts — the right place to kick off data loading.
  useEffect(() => {
    dispatch(fetchCustomers());
  }, [dispatch]);

  function handleDelete(customer: Customer) {
    const ok = confirm(`Delete ${customer.fullName}? This is a soft delete.`);
    if (!ok) return;
    // The thunk removes the row from the store on success (see the slice).
    dispatch(deleteCustomer(customer.id));
  }

  return (
    <section>
      <header className={styles.header}>
        <h1>Customers</h1>
        {/* <Link> navigates without a full page reload (SPA behaviour). */}
        <Link className="btn btn--primary" to="/customers/new">
          + New customer
        </Link>
      </header>

      {/* In JSX we use plain JS expressions for conditional rendering. */}
      {status === 'loading' && <p className="muted">Loading…</p>}

      {status === 'failed' && <p className="alert alert--error">{error}</p>}

      {status === 'succeeded' && customers.length === 0 && (
        <p className="muted">No customers yet. Create the first one!</p>
      )}

      {status === 'succeeded' && customers.length > 0 && (
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th className={styles.actions}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {/* .map() turns each customer into a <tr>. React needs a stable
                `key` on list items to track them efficiently. */}
            {customers.map((customer) => (
              <tr key={customer.id}>
                <td>{customer.fullName}</td>
                <td>{customer.email}</td>
                <td>{customer.phone}</td>
                <td className={styles.actions}>
                  <Link className="btn btn--ghost" to={`/customers/${customer.id}`}>
                    View
                  </Link>
                  <Link className="btn btn--ghost" to={`/customers/${customer.id}/edit`}>
                    Edit
                  </Link>
                  <button className="btn btn--danger" onClick={() => handleDelete(customer)}>
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </section>
  );
}

// angular-app/src/app/features/customers/customer-list/customer-list.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';

import { CustomerService } from '../../../core/customer.service';
import { Customer } from '../../../models/customer.model';

/**
 * Shows every customer in a table, with links to view/edit and a delete button.
 *
 * This is a STANDALONE component (the modern Angular default): it declares its
 * own dependencies in `imports` instead of belonging to an NgModule.
 */
@Component({
  selector: 'app-customer-list',
  // RouterLink lets us use [routerLink] in the template for navigation.
  imports: [RouterLink],
  templateUrl: './customer-list.component.html',
  styleUrl: './customer-list.component.scss'
})
export class CustomerListComponent implements OnInit {
  private readonly customerService = inject(CustomerService);

  // SIGNALS hold reactive state. When a signal's value changes, the template
  // that reads it re-renders automatically. Call a signal like a function —
  // customers() — to read it, and .set()/.update() to change it.
  readonly customers = signal<Customer[]>([]);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  // ngOnInit is a lifecycle hook: Angular calls it once, after the component is
  // created. It is the conventional place to load initial data.
  ngOnInit(): void {
    this.loadCustomers();
  }

  loadCustomers(): void {
    this.loading.set(true);
    this.error.set(null);

    // subscribe() actually fires the HTTP request. The object passed in handles
    // the two outcomes: `next` (success) and `error` (failure).
    this.customerService.getAll().subscribe({
      next: (data) => {
        this.customers.set(data);
        this.loading.set(false);
      },
      error: () => {
        this.error.set('Could not load customers. Is the API running?');
        this.loading.set(false);
      }
    });
  }

  deleteCustomer(customer: Customer): void {
    // A simple browser confirm dialog — enough for a learning app.
    const ok = confirm(`Delete ${customer.fullName}? This is a soft delete.`);
    if (!ok) {
      return;
    }

    this.customerService.delete(customer.id).subscribe({
      // On success, just reload the list so the deleted row disappears.
      next: () => this.loadCustomers(),
      error: () => this.error.set('Delete failed. Please try again.')
    });
  }
}

<!--
  Angular templates are HTML plus a little extra syntax:
    {{ value }}              interpolation: print a value
    (event)="handler()"      bind a DOM event to a method
    [prop]="expr"            bind a property/attribute to an expression
    @if / @for               the modern built-in control flow (Angular 17+)
-->
<section class="page">
  <header class="page__header">
    <h1>Customers</h1>
    <!-- routerLink navigates without a full page reload (SPA behaviour). -->
    <a class="btn btn--primary" routerLink="/customers/new">+ New customer</a>
  </header>

  <!-- @if replaces the old *ngIf. Each branch shows a different state. -->
  @if (loading()) {
    <p class="muted">Loading…</p>
  } @else if (error()) {
    <p class="alert alert--error">{{ error() }}</p>
  } @else if (customers().length === 0) {
    <p class="muted">No customers yet. Create the first one!</p>
  } @else {
    <!-- A semantic <table> is the right element for tabular data. -->
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th class="table__actions">Actions</th>
        </tr>
      </thead>
      <tbody>
        <!-- @for replaces *ngFor. `track` tells Angular how to identify each
             row so it can update the DOM efficiently. -->
        @for (customer of customers(); track customer.id) {
          <tr>
            <td>{{ customer.fullName }}</td>
            <td>{{ customer.email }}</td>
            <td>{{ customer.phone }}</td>
            <td class="table__actions">
              <a class="btn btn--ghost" [routerLink]="['/customers', customer.id]">View</a>
              <a class="btn btn--ghost" [routerLink]="['/customers', customer.id, 'edit']">Edit</a>
              <button class="btn btn--danger" (click)="deleteCustomer(customer)">Delete</button>
            </td>
          </tr>
        }
      </tbody>
    </table>
  }
</section>
