// react-app/src/features/customers/CustomerForm.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import { useAppDispatch, useAppSelector } from '../../app/hooks';
import {
  fetchCustomerById,
  createCustomer,
  updateCustomer,
  selectSelectedCustomer
} from './customersSlice';
import type { CustomerPayload } from '../../types/customer';
import styles from './CustomerForm.module.css';

// The form's field values. Same keys as CustomerPayload.
type FormValues = CustomerPayload;
type FormErrors = Partial<Record<keyof FormValues, string>>;

const EMPTY: FormValues = { firstName: '', lastName: '', email: '', phone: '' };

/**
 * ONE component for both create and edit (decided by whether the URL has an :id).
 *
 * React forms use CONTROLLED INPUTS: each <input>'s value comes from state, and
 * onChange writes back to state. State is the single source of truth, so the UI
 * always reflects it. This is React's equivalent of Angular's reactive forms.
 */
export function CustomerForm() {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = Boolean(id);

  // useState returns [value, setter]. Re-rendering happens when the setter runs.
  const [values, setValues] = useState<FormValues>(EMPTY);
  const [errors, setErrors] = useState<FormErrors>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const selected = useAppSelector(selectSelectedCustomer);

  // In edit mode, fetch the existing customer into the store on mount.
  useEffect(() => {
    if (isEditMode && id) {
      dispatch(fetchCustomerById(id));
    }
  }, [dispatch, id, isEditMode]);

  // When the fetched customer arrives, copy its fields into the form once.
  useEffect(() => {
    if (isEditMode && selected && selected.id === id) {
      setValues({
        firstName: selected.firstName,
        lastName: selected.lastName,
        email: selected.email,
        phone: selected.phone
      });
    }
  }, [isEditMode, selected, id]);

  // A single change handler for every field, keyed by the input's `name`.
  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    const { name, value } = event.target;
    // Spread the old values, then overwrite the one that changed.
    setValues((prev) => ({ ...prev, [name]: value }));
  }

  // Client-side validation that mirrors the backend's FluentValidation rules.
  function validate(v: FormValues): FormErrors {
    const next: FormErrors = {};
    if (!v.firstName.trim()) next.firstName = 'First name is required.';
    if (!v.lastName.trim()) next.lastName = 'Last name is required.';
    if (!v.email.trim()) next.email = 'Email is required.';
    else if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v.email)) next.email = 'Enter a valid email address.';
    if (!v.phone.trim()) next.phone = 'Phone is required.';
    return next;
  }

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault(); // stop the browser's default full-page form submit
    const found = validate(values);
    setErrors(found);
    if (Object.keys(found).length > 0) return;

    setSubmitting(true);
    setSubmitError(null);
    try {
      // .unwrap() makes a rejected thunk THROW here, so we can try/catch it.
      if (isEditMode && id) {
        await dispatch(updateCustomer({ id, payload: values })).unwrap();
      } else {
        await dispatch(createCustomer(values)).unwrap();
      }
      navigate('/customers'); // go back to the list on success
    } catch {
      setSubmitError('Save failed. Please check the fields and try again.');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <section>
      <header className={styles.header}>
        <h1>{isEditMode ? 'Edit customer' : 'New customer'}</h1>
        <button className="btn btn--ghost" onClick={() => navigate('/customers')}>
          ← Back to list
        </button>
      </header>

      {submitError && <p className="alert alert--error">{submitError}</p>}

      {/* onSubmit fires on the submit button or Enter key. */}
      <form className={styles.form} onSubmit={handleSubmit} noValidate>
        <div className={styles.field}>
          <label htmlFor="firstName">First name</label>
          <input id="firstName" name="firstName" value={values.firstName} onChange={handleChange} />
          {errors.firstName && <small className={styles.error}>{errors.firstName}</small>}
        </div>

        <div className={styles.field}>
          <label htmlFor="lastName">Last name</label>
          <input id="lastName" name="lastName" value={values.lastName} onChange={handleChange} />
          {errors.lastName && <small className={styles.error}>{errors.lastName}</small>}
        </div>

        <div className={styles.field}>
          <label htmlFor="email">Email</label>
          <input id="email" name="email" type="email" value={values.email} onChange={handleChange} />
          {errors.email && <small className={styles.error}>{errors.email}</small>}
        </div>

        <div className={styles.field}>
          <label htmlFor="phone">Phone</label>
          <input id="phone" name="phone" type="tel" value={values.phone} onChange={handleChange} />
          {errors.phone && <small className={styles.error}>{errors.phone}</small>}
        </div>

        <div className={styles.actions}>
          <button className="btn btn--primary" type="submit" disabled={submitting}>
            {submitting ? 'Saving…' : isEditMode ? 'Save changes' : 'Create customer'}
          </button>
          <button className="btn btn--ghost" type="button" onClick={() => navigate('/customers')}>
            Cancel
          </button>
        </div>
      </form>
    </section>
  );
}

// angular-app/src/app/features/customers/customer-form/customer-form.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';

import { CustomerService } from '../../../core/customer.service';

/**
 * ONE component handles BOTH create and edit. We decide which mode we are in by
 * checking whether the URL contains an `:id` (edit) or not (create). Reusing the
 * form like this avoids duplicating the markup and validation rules.
 *
 * We use REACTIVE FORMS: the form is defined in TypeScript (a FormGroup), giving
 * us strong typing, easy validation, and simple access to values in code.
 */
@Component({
  selector: 'app-customer-form',
  imports: [ReactiveFormsModule, RouterLink],
  templateUrl: './customer-form.component.html',
  styleUrl: './customer-form.component.scss'
})
export class CustomerFormComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly customerService = inject(CustomerService);

  // null when creating; the customer id string when editing.
  private editingId: string | null = null;

  readonly submitting = signal(false);
  readonly error = signal<string | null>(null);

  // The form definition. Each control gets an initial value and a list of
  // synchronous validators that mirror the backend's FluentValidation rules.
  // `nonNullable` means the controls are typed as `string` (not `string | null`)
  // and reset back to their initial value rather than null — which makes
  // getRawValue() line up cleanly with our CustomerPayload type.
  readonly form = this.fb.nonNullable.group({
    firstName: ['', [Validators.required, Validators.maxLength(50)]],
    lastName: ['', [Validators.required, Validators.maxLength(50)]],
    email: ['', [Validators.required, Validators.email]],
    phone: ['', [Validators.required, Validators.maxLength(30)]]
  });

  // A getter the template can read to switch labels/titles between modes.
  get isEditMode(): boolean {
    return this.editingId !== null;
  }

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.editingId = id;
      // In edit mode, fetch the existing values and pre-fill the form.
      this.customerService.getById(id).subscribe({
        next: (customer) => {
          this.form.patchValue({
            firstName: customer.firstName,
            lastName: customer.lastName,
            email: customer.email,
            phone: customer.phone
          });
        },
        error: () => this.error.set('Could not load the customer to edit.')
      });
    }
  }

  // Small helper so the template can ask "should I show an error for this field?"
  // True only when the control is invalid AND the user has interacted with it.
  showError(controlName: string): boolean {
    const control = this.form.get(controlName);
    return !!control && control.invalid && (control.dirty || control.touched);
  }

  submit(): void {
    // If the form is invalid, mark everything as touched so all error messages
    // appear at once, then stop.
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.submitting.set(true);
    this.error.set(null);

    // getRawValue() returns a plain object matching CustomerPayload.
    const payload = this.form.getRawValue();

    const request$ = this.isEditMode
      ? this.customerService.update(this.editingId!, payload)
      : this.customerService.create(payload);

    request$.subscribe({
      next: () => {
        this.submitting.set(false);
        // On success, go back to the list.
        this.router.navigate(['/customers']);
      },
      error: () => {
        this.submitting.set(false);
        this.error.set('Save failed. Please check the fields and try again.');
      }
    });
  }
}

<section class="page">
  <header class="page__header">
    <!-- The title changes based on the mode getter in the component. -->
    <h1>{{ isEditMode ? 'Edit customer' : 'New customer' }}</h1>
    <a class="btn btn--ghost" routerLink="/customers">← Back to list</a>
  </header>

  @if (error()) {
    <p class="alert alert--error">{{ error() }}</p>
  }

  <!--
    [formGroup] binds this <form> to the FormGroup in TypeScript.
    (ngSubmit) fires when the form is submitted (Enter key or submit button).
    Each input uses formControlName to link to a control by name.
  -->
  <form class="form" [formGroup]="form" (ngSubmit)="submit()">
    <div class="form__field">
      <!-- <label for>/id pairing makes the label clickable and screen-reader
           friendly — an easy, important accessibility win. -->
      <label for="firstName">First name</label>
      <input id="firstName" type="text" formControlName="firstName" />
      @if (showError('firstName')) {
        <small class="form__error">First name is required (max 50 characters).</small>
      }
    </div>

    <div class="form__field">
      <label for="lastName">Last name</label>
      <input id="lastName" type="text" formControlName="lastName" />
      @if (showError('lastName')) {
        <small class="form__error">Last name is required (max 50 characters).</small>
      }
    </div>

    <div class="form__field">
      <label for="email">Email</label>
      <input id="email" type="email" formControlName="email" />
      @if (showError('email')) {
        <small class="form__error">A valid email address is required.</small>
      }
    </div>

    <div class="form__field">
      <label for="phone">Phone</label>
      <input id="phone" type="tel" formControlName="phone" />
      @if (showError('phone')) {
        <small class="form__error">Phone is required (max 30 characters).</small>
      }
    </div>

    <div class="form__actions">
      <!-- [disabled] prevents double-submits while the request is in flight. -->
      <button class="btn btn--primary" type="submit" [disabled]="submitting()">
        {{ submitting() ? 'Saving…' : (isEditMode ? 'Save changes' : 'Create customer') }}
      </button>
      <a class="btn btn--ghost" routerLink="/customers">Cancel</a>
    </div>
  </form>
</section>
